version: "3"
services:
  postgresSQL:
    image: postgres:latest
    container_name: postgresSQL
    hostname: postgresSQL
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      webproxy:
         ipv4_address: 192.168.1.2
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    hostname: mongoDB
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      webproxy:
         ipv4_address: 192.168.1.3
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    hostname: pgadmin4    
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL:  pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - /var/lib/pgadmin:/var/lib/pgadmin
    networks:
      webproxy:
         ipv4_address: 192.168.1.4
    links:
      - postgresSQL:postgres
  rancher:
    image: rancher/server:stable
    container_name: rancher
    restart: unless-stopped
    hostname: rancher
    networks:
       webproxy: 
         ipv4_address: 192.168.1.5

networks:
  webproxy:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
