version: "3"
services:
  postgresSQL:
    image: postgres
    container_name: postgresSQL
    hostname: postgresSQL
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      webproxy:
         ipv4_address: 192.168.1.2
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    hostname: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      webproxy:
         ipv4_address: 192.168.1.3
  pgadmin4:
    image: fenglc/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4    
    environment:
      DEFAULT_USER:  pgadmin4@pgadmin.org
      DEFAULT_PASSWORD: admin
    networks:
      webproxy:
         ipv4_address: 192.168.1.4
    links:
      - postgresSQL:postgres
  rancher:
    image: rancher/server:stable
    container_name: rancher
    hostname: rancher
    networks:
       webproxy: 
         ipv4_address: 192.168.1.5

networks:
  webproxy:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
